---
- name: Fact dock user
  set_fact:
    dock_user: '{{ dock_user | default(homebrew_user) | default(ansible_user_id) }}'
  tags:
    - dock

- become: '{{ (dock_user != ansible_user_id) | bool }}'
  become_user: '{{ dock_user }}'
  block:
    - name: Install required package
      ignore_errors: True
      homebrew:
        name: dockutil
        state: present
      tags:
        - dock

    - name: Aple interface style
      notify:
        - Kill dock
      osx_defaults:
        domain: NSGlobalDomain
        key: AppleInterfaceStyle
        type: string
        value: '{{ dock_interface_style }}'
        state: present
      tags:
        - dock

    - name: Auto hide
      notify:
        - Kill dock
      osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: '{{ dock_auto_hide }}'
        state: present
      tags:
        - dock

    - name: Show process indicator
      notify:
        - Kill dock
      osx_defaults:
        domain: com.apple.dock
        key: show-process-indicators
        type: bool
        value: '{{ dock_show_process_indicator }}'
        state: present
      tags:
        - dock

    - name: Launch animation
      notify:
        - Kill dock
      osx_defaults:
        domain: com.apple.dock
        key: launchanim
        type: bool
        value: '{{ dock_launch_animation }}'
        state: present
      tags:
        - dock

    - name: Large size
      notify:
        - Kill dock
      osx_defaults:
        domain: com.apple.dock
        key: largesize
        type: float
        value: '{{ dock_large_size }}'
        state: present
      tags:
        - dock

    - name: Tile size
      notify:
        - Kill dock
      osx_defaults:
        domain: com.apple.dock
        key: tilesize
        type: float
        value: '{{ dock_tile_size }}'
        state: present
      tags:
        - dock

    - name: Show recent apps
      notify:
        - Kill dock
      osx_defaults:
        domain: com.apple.dock
        key: show-recents
        type: bool
        value: '{{ dock_show_recent_apps }}'
        state: present
      tags:
        - dock

    - name: Enable magnification
      notify:
        - Kill dock
      osx_defaults:
        domain: com.apple.dock
        key: magnification
        type: bool
        value: '{{ dock_magnification }}'
        state: present
      tags:
        - dock

    - name: Minimize to application
      notify:
        - Kill dock
      osx_defaults:
        domain: com.apple.dock
        key: minimize-to-application
        type: bool
        value: '{{ dock_minimize_to_app }}'
        state: present
      tags:
        - dock

    - name: Show hidden
      notify:
        - Kill dock
      osx_defaults:
        domain: com.apple.dock
        key: showhidden
        type: bool
        value: '{{ dock_show_hidden }}'
        state: present
      tags:
        - dock

    - name: Corner action topleft
      notify:
        - Kill dock
      osx_defaults:
        domain: com.apple.dock
        key: wvous-tl-corner
        type: int
        value: '{{ dock_hot_corner_top_left }}'
        state: present
      tags:
        - dock

    - name: Corner action bottomleft
      notify:
        - Kill dock
      osx_defaults:
        domain: com.apple.dock
        key: wvous-bl-corner
        type: int
        value: '{{ dock_hot_corner_bottom_left }}'
        state: present
      tags:
        - dock

    - name: Corner action topright
      notify:
        - Kill dock
      osx_defaults:
        domain: com.apple.dock
        key: wvous-tr-corner
        type: int
        value: '{{ dock_hot_corner_top_right }}'
        state: present
      tags:
        - dock

    - name: Corner action bottomright
      notify:
        - Kill dock
      osx_defaults:
        domain: com.apple.dock
        key: wvous-br-corner
        type: int
        value: '{{ dock_hot_corner_bottom_right }}'
        state: present
      tags:
        - dock

    - name: Check defined apps
      register: dock_defined_apps
      check_mode: False
      failed_when: dock_defined_apps.rc != 0
      changed_when: False
      shell: /usr/local/bin/dockutil --list | cut -f2
      tags:
        - dock

    - name: Check requested apps
      set_fact:
        dock_requested_apps: "{{ (dock_general_apps + dock_other_apps) | map('regex_replace', '(.+)', 'file://\\1/') | map('regex_replace', ' ', '%20') | list }}"
      tags:
        - dock

    - name: Diff between apps
      set_fact:
        dock_diff_apps: "{{ dock_defined_apps.stdout_lines | difference(dock_requested_apps) | length > 0 or dock_requested_apps | difference(dock_defined_apps.stdout_lines) | length > 0 }}"
      tags:
        - dock

    - name: Clear dock apps
      when: dock_diff_apps
      register: dock_remove
      failed_when: dock_remove.rc != 0
      changed_when: True
      command: /usr/local/bin/dockutil --remove all
      tags:
        - dock

    - name: Add general apps
      when: dock_diff_apps
      failed_when: False
      changed_when: True
      loop: '{{ dock_general_apps }}'
      command: /usr/local/bin/dockutil --add "{{ item.name | default(item) }}" --section apps{% if item.type | default(False) %} --type {{ item.type }}{% endif %}{% if item.label | default(False) %} --label {{ item.label }}{% endif %}
      tags:
        - dock

    - name: Add other apps
      when: dock_diff_apps
      failed_when: False
      changed_when: True
      loop: '{{ dock_other_apps }}'
      command: /usr/local/bin/dockutil --add "{{ item.name | default(item) }}" --section others{% if item.type | default(False) %} --type {{ item.type }}{% endif %}{% if item.label | default(False) %} --label {{ item.label }}{% endif %}
      tags:
        - dock

...
